name: Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:

  test:
    strategy:
      max-parallel: 9
      matrix:
        go-version: [1.13.x, 1.14.x, 1.15.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Go on the Container
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Test the Go code
        run: go test -v ./...